### ISSUE TITLE
holding mouse button keeps playing attack combo

### ISSUE THREAD

**Issue by QaleQ** [nihanbir/WayOfHoof#13]
.. but only the first click actually registers attack.
desired solution is probably to prevent animations from playing while holding the mouse button, rather than registering each animation as an attack

**Comment by nihanbir** [comment]
[This ticket will solve this issue](https://wayofhoofprototype.atlassian.net/browse/PIG-33?atlOrigin=eyJpIjoiNTgxZTExOThlMWUyNDI5OTg1NTU2ZjI4MmUzMzEzMzEiLCJwIjoiaiJ9)

**Comment by nihanbir** [comment]
**EnableAttackHitbox node is removed from the event**
![image](https://github.com/nihanbir/WayOfHoof/assets/112477158/8121d53a-a643-4a17-9683-156cc0b9bfa7)

**EnableAttackHitbox node is added on AttackLanded notify
Added CanCombo notify for designers to have more freedom on combos**
![image](https://github.com/nihanbir/WayOfHoof/assets/112477158/8111183e-a19b-4a55-a248-6773c26099c2)
