### ISSUE TITLE
Player slides in shimmy state after hooked state

### ISSUE THREAD

**Issue by nihanbir** [nihanbir/WayOfHoof#60]
Player slides in shimmy state after hooked state

![Untitled video - Made with Clipchamp (5)](https://github.com/nihanbir/WayOfHoof/assets/112477158/c3a84353-140f-489a-b0ac-3f0e56fb5ee9)

_Originally posted by @nihanbir in https://github.com/nihanbir/WayOfHoof/issues/57#issuecomment-1875369368_

**Comment by QaleQ** [comment]
fixed
